### ISSUE TITLE
can you add a url scheme，

### ISSUE THREAD

**Issue by daizy008** [tako0910/LivePhotoMaker#1]
so that I can use workflow app make live photos more automatic in iOS device。

**Comment by tako0910** [comment]
1. Define URL Scheme like this screenshot.
![screen shot 2017-10-01 at 20 35 05](https://user-images.githubusercontent.com/2842469/31054191-4ebbb932-a6e8-11e7-9769-6bd904ff5537.png)

2.  Add this code in Appdelegate.m
```objective-c
- (BOOL)application:(UIApplication*)application openURL:(NSURL*)url sourceApplication:
(NSString*)sourceApplication annotation:(id)annotation
{
    // receive url parameters here.
    return YES;
}
```

3. Open Safari, and type "livephotomaker://test" to confirm that launch this app.

**Comment by daizy008** [comment]
thank you
tako <notifications@github.com>于2017年10月1日 周日下午7:44写道：
